In [1]:
#importing necessary libraries to implement ML model and assess accuracy.

import numpy as np
import pandas as pd
import os
import re
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from textblob import TextBlob as TB

C:\Users\Aranya\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


### Getting sentiment polarity scores using textblob

In [2]:
df = pd.read_csv(r"PATH", encoding = "utf-8") #Add path to required csv file
df

id        date      time   
0     1.280000e+18  12-07-2020  01:21:29  \
1     1.310000e+18   9/17/2020  06:51:16   
2     1.370000e+18  20-03-2021  13:13:23   
3     1.380000e+18  17-04-2021  18:16:57   
4     1.400000e+18  05-06-2021  13:34:46   
...            ...         ...       ...   
2622  1.610000e+18  24-12-2022  05:35:51   
2623  1.610000e+18  24-12-2022  13:43:47   
2624  1.610000e+18  12-01-2023  06:24:26   
2625  1.620000e+18  20-01-2023  10:56:06   
2626  1.630000e+18  27-02-2023  14:05:01   

                                                   text       long        lat   
0     Another lockdown ...\n 😁😆😅🤣😂😂 @ Pune, Maharash...  73.856700  18.520300  \
1     Just posted a photo @ Lockdown 2020 https://t....  72.834830  18.940170   
2     109 Covid cases in Vasai-Virar today. \n\nWhat...  72.808056  19.419102   
3          Defeated COVID-19??? https://t.co/mO3dQeb9Xl  72.827369  19.381244   
4     Business k Liya lockdown m nyi rona¡ @ India h...  77.000000  21.000000   
...                                                 ...        ...        ...   
2622  'Work' from home @ Pune, Maharashtra https://t...  73.856700  18.520300   
2623  Everyone, Please start using this.\n\n#coronai...  77.000000  21.000000   
2624  Expose brick work ..\n\n#stonemasnoryindia \n#...  75.883300  19.833300   
2625  Work from the real Home but here work has a de...  73.778458  18.392663   
2626  24 hours until the CfP for "Battery Materials ...  73.854454  18.521428   

     country         city lang   
0      India         Pune   en  \
1      India       Mumbai   en   
2      India       Mumbai   en   
3      India       Mumbai   en   
4      India  Maharashtra   en   
...      ...          ...  ...   
2622   India         Pune   en   
2623   India  Maharashtra   en   
2624   India        Jalna   en   
2625   India       Haveli   en   
2626   India         Pune   en   

                                                   geom   
0     0101000020E6100000ED9E3C2CD4765240DA1B7C613285...  \
1     0101000020E61000000FEECEDA6D35524029AE2AFBAEF0...   
2     0101000020E6100000909B4431B73352400407514A4A6B...   
3     0101000020E610000083422D9BF33452408854283D9961...   
4     0101000020E61000000000000000405340000000000000...   
...                                                 ...   
2622  0101000020E6100000ED9E3C2CD4765240DA1B7C613285...   
2623  0101000020E61000000000000000405340000000000000...   
2624  0101000020E6100000A323B9FC87F85240BEC1172653D5...   
2625  0101000020E61000007D40C141D2715240C25C41898564...   
2626  0101000020E6100000B8DB3F60AF765240FC372F4E7C85...   

                                           cleaned_text  
0                             lockdown pune maharashtra  
1                       just posted photo lockdown 2020  
2     109 covid cases vasaivirar today whats going s...  
3                                      defeated covid19  
4             business k liya lockdown m nyi rona india  
...                                                 ...  
2622                         work home pune maharashtra  
2623  start using coronaisback coronaprecautions cor...  
2624  expose brick work stonemasnoryindia stonewalls...  
2625  work real home work deeper meaning siddhanath ...  
2626  24 hours cfp battery materials market 2021 glo...  

[2627 rows x 11 columns]

In [3]:
score = []
sentiment = []
label = []

for i in range(len(df)):
    fullText = df.loc[i,'cleaned_text']
    fullText = str(fullText)
    fullText = fullText.encode('utf-8')
    sentimentScore = TB(str(fullText)).sentiment.polarity
    sentimentScore = float(sentimentScore)
    score.append(sentimentScore)
    if (sentimentScore < -0.25):
        sentiment.append('Negative')
        label.append(-1)
    elif (sentimentScore > 0.25):
        sentiment.append('Positive')
        label.append(1)
    else:
        sentiment.append('Neutral')
        label.append(0)

df['textblob_Score'] = score
df['textblob_Sentiment'] = sentiment
df['textblob_Label'] = label

df

id        date      time   
0     1.280000e+18  12-07-2020  01:21:29  \
1     1.310000e+18   9/17/2020  06:51:16   
2     1.370000e+18  20-03-2021  13:13:23   
3     1.380000e+18  17-04-2021  18:16:57   
4     1.400000e+18  05-06-2021  13:34:46   
...            ...         ...       ...   
2622  1.610000e+18  24-12-2022  05:35:51   
2623  1.610000e+18  24-12-2022  13:43:47   
2624  1.610000e+18  12-01-2023  06:24:26   
2625  1.620000e+18  20-01-2023  10:56:06   
2626  1.630000e+18  27-02-2023  14:05:01   

                                                   text       long        lat   
0     Another lockdown ...\n 😁😆😅🤣😂😂 @ Pune, Maharash...  73.856700  18.520300  \
1     Just posted a photo @ Lockdown 2020 https://t....  72.834830  18.940170   
2     109 Covid cases in Vasai-Virar today. \n\nWhat...  72.808056  19.419102   
3          Defeated COVID-19??? https://t.co/mO3dQeb9Xl  72.827369  19.381244   
4     Business k Liya lockdown m nyi rona¡ @ India h...  77.000000  21.000000   
...                                                 ...        ...        ...   
2622  'Work' from home @ Pune, Maharashtra https://t...  73.856700  18.520300   
2623  Everyone, Please start using this.\n\n#coronai...  77.000000  21.000000   
2624  Expose brick work ..\n\n#stonemasnoryindia \n#...  75.883300  19.833300   
2625  Work from the real Home but here work has a de...  73.778458  18.392663   
2626  24 hours until the CfP for "Battery Materials ...  73.854454  18.521428   

     country         city lang   
0      India         Pune   en  \
1      India       Mumbai   en   
2      India       Mumbai   en   
3      India       Mumbai   en   
4      India  Maharashtra   en   
...      ...          ...  ...   
2622   India         Pune   en   
2623   India  Maharashtra   en   
2624   India        Jalna   en   
2625   India       Haveli   en   
2626   India         Pune   en   

                                                   geom   
0     0101000020E6100000ED9E3C2CD4765240DA1B7C613285...  \
1     0101000020E61000000FEECEDA6D35524029AE2AFBAEF0...   
2     0101000020E6100000909B4431B73352400407514A4A6B...   
3     0101000020E610000083422D9BF33452408854283D9961...   
4     0101000020E61000000000000000405340000000000000...   
...                                                 ...   
2622  0101000020E6100000ED9E3C2CD4765240DA1B7C613285...   
2623  0101000020E61000000000000000405340000000000000...   
2624  0101000020E6100000A323B9FC87F85240BEC1172653D5...   
2625  0101000020E61000007D40C141D2715240C25C41898564...   
2626  0101000020E6100000B8DB3F60AF765240FC372F4E7C85...   

                                           cleaned_text  textblob_Score   
0                             lockdown pune maharashtra           0.000  \
1                       just posted photo lockdown 2020           0.000   
2     109 covid cases vasaivirar today whats going s...          -0.175   
3                                      defeated covid19           0.000   
4             business k liya lockdown m nyi rona india           0.000   
...                                                 ...             ...   
2622                         work home pune maharashtra           0.000   
2623  start using coronaisback coronaprecautions cor...           0.000   
2624  expose brick work stonemasnoryindia stonewalls...           0.000   
2625  work real home work deeper meaning siddhanath ...           0.200   
2626  24 hours cfp battery materials market 2021 glo...           0.250   

     textblob_Sentiment  textblob_Label  
0               Neutral               0  
1               Neutral               0  
2               Neutral               0  
3               Neutral               0  
4               Neutral               0  
...                 ...             ...  
2622            Neutral               0  
2623            Neutral               0  
2624            Neutral               0  
2625            Neutral               0  
2626            Neutral          

### Sentiment Classification using supervised machine learning algorithm

In [4]:
data1=pd.read_csv(r"PATH", encoding = "utf-8") #Add path to required csv file
#data1

In [5]:
#Divide data into training and testing set - 70:30

from sklearn.model_selection import train_test_split

X = data1['cleaned_text']
y = data1['textblob_Label']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10, train_size = .7,shuffle = True)

In [6]:
# BAG OF WORDS implementation using count vector - bigram method

from sklearn.feature_extraction.text import CountVectorizer

cVec=CountVectorizer(ngram_range=(1,2))
cVec_train=cVec.fit_transform(X_train.values.astype('U'))
cVec_test = cVec.transform(X_test.values.astype('U'))
data_count = cVec.transform(data1.iloc[:,10].values.astype('U'))

In [7]:
#Parameters for checking accuracy.

def classification_params(test,predic):

    from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
    
    matrix=confusion_matrix(test,predic)
    print(matrix)
    score=accuracy_score(test,predic)
    print(score)
    report=classification_report(test,predic)
    print(report)
    return matrix, score, report

In [8]:
def sentiment(score):
    sentiment = []
    for i in range(len(data1)):
        sentimentScore = data1.loc[i,score]
        if (sentimentScore < -0.25):
            sentiment.append('Negative')
        elif (sentimentScore > 0.25):
            sentiment.append('Positive')
        else:
            sentiment.append('Neutral')
    return sentiment

#### 1. Random Forest

In [9]:
#implement RandomForest Classifier for count vector

from sklearn.ensemble import RandomForestClassifier

randomclassifier=RandomForestClassifier(n_estimators=50,criterion='entropy')

randomclassifier.fit(cVec_train,y_train)
random_count_pred = randomclassifier.predict(cVec_test)

classification_params(y_test,random_count_pred)

[[  0  24   0]
 [  1 546  14]
 [  0  84 120]]
0.844106463878327
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        24
           0       0.83      0.97      0.90       561
           1       0.90      0.59      0.71       204

    accuracy                           0.84       789
   macro avg       0.58      0.52      0.54       789
weighted avg       0.83      0.84      0.82       789



(array([[  0,  24,   0],
        [  1, 546,  14],
        [  0,  84, 120]], dtype=int64),
 0.844106463878327,
 '              precision    recall  f1-score   support\n\n          -1       0.00      0.00      0.00        24\n           0       0.83      0.97      0.90       561\n           1       0.90      0.59      0.71       204\n\n    accuracy                           0.84       789\n   macro avg       0.58      0.52      0.54       789\nweighted avg       0.83      0.84      0.82       789\n')

In [10]:
data1['Random_score'] = randomclassifier.predict(data_count)

data1['Random_sentiment'] = sentiment('Random_score')

#### 2. Support Vector Machine

In [11]:
# Perform classification with SVM, kernel=linear
from sklearn import svm

classifier_linear = svm.SVC(kernel='linear')

classifier_linear.fit(cVec_train, y_train)
prediction_linear = classifier_linear.predict(cVec_test)

classification_params(y_test,prediction_linear)

[[  1  23   0]
 [  1 544  16]
 [  0  84 120]]
0.8428390367553865
              precision    recall  f1-score   support

          -1       0.50      0.04      0.08        24
           0       0.84      0.97      0.90       561
           1       0.88      0.59      0.71       204

    accuracy                           0.84       789
   macro avg       0.74      0.53      0.56       789
weighted avg       0.84      0.84      0.82       789



(array([[  1,  23,   0],
        [  1, 544,  16],
        [  0,  84, 120]], dtype=int64),
 0.8428390367553865,
 '              precision    recall  f1-score   support\n\n          -1       0.50      0.04      0.08        24\n           0       0.84      0.97      0.90       561\n           1       0.88      0.59      0.71       204\n\n    accuracy                           0.84       789\n   macro avg       0.74      0.53      0.56       789\nweighted avg       0.84      0.84      0.82       789\n')

In [12]:
data1['svc_lin_score'] = classifier_linear.predict(data_count)

data1['svc_lin_sentiment'] = sentiment('svc_lin_score')

In [13]:
# Perform classification with SVM, kernel=rbf


classifier_rbf = svm.SVC()

classifier_rbf.fit(cVec_train, y_train)
prediction_rbf = classifier_rbf.predict(cVec_test)

classification_params(y_test,prediction_rbf)

[[  0  24   0]
 [  1 557   3]
 [  0 136  68]]
0.7921419518377694
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        24
           0       0.78      0.99      0.87       561
           1       0.96      0.33      0.49       204

    accuracy                           0.79       789
   macro avg       0.58      0.44      0.46       789
weighted avg       0.80      0.79      0.75       789



(array([[  0,  24,   0],
        [  1, 557,   3],
        [  0, 136,  68]], dtype=int64),
 0.7921419518377694,
 '              precision    recall  f1-score   support\n\n          -1       0.00      0.00      0.00        24\n           0       0.78      0.99      0.87       561\n           1       0.96      0.33      0.49       204\n\n    accuracy                           0.79       789\n   macro avg       0.58      0.44      0.46       789\nweighted avg       0.80      0.79      0.75       789\n')

In [14]:
data1['svc_rbf_score'] = classifier_rbf.predict(data_count)

data1['svc_rbf_sentiment'] = sentiment('svc_rbf_score')